# Generated by Django 4.0.6 on 2022-08-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bridalsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='models',
            new_name='offer',
        ),
    ]
